#!/usr/bin/env python
"""Distill coaching transcripts into the knowledge file used by the AI analysis prompts.

Reads every markdown transcript in how_to_jump/ and produces
worker/app/knowledge/regular_jump.md. Re-run whenever transcripts are added:

    .venv/bin/python scripts/distill_knowledge.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TRANSCRIPTS_DIR = REPO_ROOT / "how_to_jump"
OUTPUT_PATH = REPO_ROOT / "worker" / "app" / "knowledge" / "regular_jump.md"

SYSTEM = """You are distilling mountain-bike coaching video transcripts into a compact knowledge base that a vision AI will use to judge video frames of riders jumping. Write for that AI reader: concrete, visual, deduplicated across coaches.

Produce a markdown document with EXACTLY these sections:

# Regular jump — coaching knowledge

## Phases and correct technique
One subsection per phase (approach, compression/loading, takeoff/extension, air, landing). For each: what the rider should do, and 2-4 VISUAL CUES — what a correct frame of this phase looks like (body shape, limb positions, bike attitude).

## Common mistakes
One subsection per named mistake (e.g. dead sailor, nose dive, arms-first extension / bucking, weight too far back, pulling up instead of pumping, stiff landing, taking off crooked...). For each: the visual signature in a frame or frame sequence, the usual cause, the consequence, and the coaching fix in rider language.

## Frame-selection guidance
Which exact moments of a jump matter most for judging technique, and how to recognize each in a still frame.

## Coaching voice
5-8 short rules for how these coaches phrase feedback (tone, encouragement, safety framing, progression advice).

Rules: merge agreeing coaches into one statement; if coaches disagree, say so in one line. Keep the whole document under 250 lines. No filler, no video-specific anecdotes, no coach names in the body."""


def main() -> int:
    try:
        from dotenv import load_dotenv

        load_dotenv(REPO_ROOT / ".env")
    except ImportError:
        pass

    import anthropic

    transcripts = sorted(TRANSCRIPTS_DIR.glob("*.md"))
    if not transcripts:
        print(f"No transcripts found in {TRANSCRIPTS_DIR}")
        return 1

    parts = []
    for path in transcripts:
        parts.append(f"\n\n===== TRANSCRIPT: {path.name} =====\n\n{path.read_text(encoding='utf-8')}")
    corpus = "".join(parts)
    print(f"Distilling {len(transcripts)} transcripts ({len(corpus) // 1000}KB)...")

    client = anthropic.Anthropic()
    with client.messages.stream(
        model="claude-opus-4-8",
        max_tokens=16000,
        thinking={"type": "adaptive"},
        system=SYSTEM,
        messages=[{"role": "user", "content": corpus}],
    ) as stream:
        response = stream.get_final_message()

    text = "".join(block.text for block in response.content if block.type == "text")
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = (
        "<!-- Generated by worker/scripts/distill_knowledge.py from how_to_jump/ transcripts. -->\n"
        f"<!-- Model: {response.model}. Re-run the script after adding transcripts. -->\n\n"
    )
    OUTPUT_PATH.write_text(header + text.strip() + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH} ({len(text) // 1000}KB, usage: {response.usage.input_tokens} in / {response.usage.output_tokens} out)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
